# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Vettore TI\Desktop\layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from selenium import webdriver
import time
from webdriver_manager.chrome import ChromeDriverManager 
from selenium.webdriver.common.keys import Keys
from PyQt5 import QtCore, QtGui, QtWidgets
#from test import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(441, 417)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 441, 401))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label.setObjectName("label")
        self.campoTel = QtWidgets.QLineEdit(self.tab)
        self.campoTel.setGeometry(QtCore.QRect(10, 30, 191, 20))
        self.campoTel.setObjectName("campoTel")
        

        self.addLista = QtWidgets.QPushButton(self.tab)
        self.addLista.setGeometry(QtCore.QRect(10, 60, 75, 23))
        self.addLista.setObjectName("addLista")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 61, 16))
        self.label_2.setObjectName("label_2")
        self.campoMsg = QtWidgets.QLineEdit(self.tab)
        self.campoMsg.setGeometry(QtCore.QRect(10, 130, 191, 20))
        self.campoMsg.setObjectName("campoMsg")
        self.addTxt = QtWidgets.QPushButton(self.tab)
        self.addTxt.setGeometry(QtCore.QRect(10, 160, 75, 23))
        self.addTxt.setObjectName("addTxt")
        self.editarLista = QtWidgets.QPushButton(self.tab)
        self.editarLista.setGeometry(QtCore.QRect(130, 60, 75, 23))
        self.editarLista.setObjectName("editarLista")
        self.editarTxt = QtWidgets.QPushButton(self.tab)
        self.editarTxt.setGeometry(QtCore.QRect(130, 160, 75, 23))
        self.editarTxt.setObjectName("editarTxt")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 441, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #magica
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.addLista.pressed.connect(self.campoTel.clear)
        self.addLista.released.connect(self.carregarTel)

        self.addTxt.pressed.connect(self.campoMsg.clear)
        self.addTxt.released.connect(self.carregarMsg)

        self.editarTxt.pressed.connect(self.campoMsg.clear)
        self.editarTxt.released.connect(self.enviarMsg)
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Telefone:"))
        self.addLista.setText(_translate("MainWindow", "Adicionar lista"))
        self.label_2.setText(_translate("MainWindow", "Mensagem:"))
        self.addTxt.setText(_translate("MainWindow", "Adicionar txt"))
        self.editarLista.setText(_translate("MainWindow", "Editar lista"))
        self.editarTxt.setText(_translate("MainWindow", "Enviar txt"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))

    def carregarTel(self):
        numeros = open("qb.txt","r")
        print("Lista Carregada")
        return numeros

    def carregarMsg(self):
        msg = open("texto.txt","r",encoding="utf8")
        mensagem = str(msg.read())
        print("Mensagem Carregada")
        return mensagem

    def enviarMsg(self):
        from test import enviar_mensagem
        time.sleep(5)
        novo = webdriver.Chrome(ChromeDriverManager().install())
        for linha in numeros:
            numero = linha.split()
            time.sleep(5)
            novo.get('https://web.whatsapp.com/send?phone=%5B%27{}%27%5D&text={}'.format(numero,""))
            time.sleep(5)
            enviar_mensagem(mensagem)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
    numeros = ""
    mensagem = ""

